---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 28.8.2
    digest: sha256:e09bceb941fb8b208760906f1dc55cb5219e3cbc3cbf9c3e134c0c77f7bbcba8
  url: oci://oci.trueforge.org/truecharts/immich
