---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 28.8.0
    digest: sha256:8342a693ea2c750fa1c7a7ea858053dcb0cdb61c41f4bb2dc53b6f3cee3b3aae
  url: oci://oci.trueforge.org/truecharts/immich
