---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
spec:
  releaseName: *app
  dependsOn:
    - name: ${APP}-proxy
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      radarr:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          waitpsql:
            enabled: true
            image:
              repository: ghcr.io/home-operations/busybox
              tag: 1.38.0@sha256:7e2c04dd50ede647bf4a7a4c8dbd629dd4971cd139b9b88fb22bfc3c7a6c13df
              pullPolicy: IfNotPresent
            command:
              [
                "sh",
                "-c",
                'until nc -vz $${POD_NAME}.$${POD_NAMESPACE}.svc.cluster.local 5432; do echo "Waiting for postgres..."; sleep 3; done;',
              ]
            env:
              POD_NAME: postgres-db-rw # service name for psql rw operations
              POD_NAMESPACE: ${psql_database_namespace}

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.2.1.10461@sha256:a566e7d364b96ce8ffb1b582266e656c69f3a12dec289d72bb0daa647ed4725e
            env:
              TZ: Europe/Paris
              # Categories are listed here https://github.com/Radarr/Radarr/tree/develop/src/NzbDrone.Common/Options
              RADARR__AUTH__APIKEY:
                secretKeyRef:
                  name: ${SECRET_KEY_NAME}
                  key: secretKey
              RADARR__APP__INSTANCENAME: Radarr
              RADARR__APP__THEME: dark
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__LOG__DBENABLED: "False"
              RADARR__LOG__LEVEL: info
              RADARR__SERVER__PORT: &port ${GATEWAY_SVC_PORT}
              RADARR__UPDATE__BRANCH: develop
              RADARR__POSTGRES__HOST: postgres-db-rw.${psql_database_namespace}.svc.cluster.local
              RADARR__POSTGRES__PORT: "5432"
              RADARR__POSTGRES__USER: ${PSQL_DB_USER}
              RADARR__POSTGRES__PASSWORD:
                secretKeyRef:
                  name: ${PSQL_DB_USER}-db-creds
                  key: password
              RADARR__POSTGRES__MAINDB: ${PSQL_DB_NAME}
              RADARR__POSTGRES__LOGDB: ${PSQL_LOG_DB_NAME}
            ports:
              - containerPort: *port
                name: http
                protocol: TCP
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              limits:
                memory: 800Mi
              requests:
                cpu: 200m
                memory: 200Mi
          exportarr:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.3.0@sha256:af535d94061cf97a52e1661945ffba78c03f9443eae7c0da1a80a5a4be56b520
            args:
              - radarr
            env:
              INTERFACE: 0.0.0.0
              PORT: &exporterPort 7879
              URL: "http://radarr:${GATEWAY_SVC_PORT}"
              # additional metrics (slow)
              # ENABLE_ADDITIONAL_METRICS: false
              # enable gathering unknown queue items
              # ENABLE_UNKNOWN_QUEUE_ITEMS: false
              CONFIG: "/config/config.xml"
              API_KEY:
                secretKeyRef:
                  name: ${SECRET_KEY_NAME}
                  key: secretKey
            ports:
              - containerPort: *exporterPort
                name: http
                protocol: TCP
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *exporterPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *exporterPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              limits:
                memory: 50Mi
              requests:
                cpu: 10m
                memory: 20Mi

    service:
      app:
        controller: radarr
        ports:
          http:
            port: *port
          metrics:
            port: *exporterPort
    serviceMonitor:
      app:
        endpoints:
          - port: metrics

    persistence:
      config:
        type: emptyDir
      tmp:
        type: emptyDir
      downloads:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_download}
        globalMounts:
          - path: /downloads
      media3:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_media_3}
        globalMounts:
          - path: "/shared/media3/"
      media4:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_media_4}
        globalMounts:
          - path: "/shared/media4/"
