---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: radarr
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 27.6.0
    digest: sha256:82572b650fc1a487f3a3019b0ccee4b78b9f7f5e1c92f9403e5f46627ce14e2e
  url: oci://oci.trueforge.org/truecharts/radarr
