---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: radarr
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 27.4.2
    digest: sha256:d864e42c2a2e3254f8740f9faaaee21068ff46e87f719cf0b9ad88b66b78ca34
  url: oci://oci.trueforge.org/truecharts/radarr
