---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  releaseName: grafana-operator
  chartRef:
    kind: OCIRepository
    name: grafana-operator
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3
    crds: CreateReplace
    strategy:
      name: RetryOnFailure # retry failed upgrades instead of rollback
      retryInterval: 5m
  upgrade:
    crds: CreateReplace

  values:
    # https://github.com/grafana/grafana-operator/blob/master/deploy/helm/grafana-operator/values.yaml
    dashboard:
      enabled: true
    serviceMonitor:
      enabled: true

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
