---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyfin
spec:
  releaseName: *app
  dependsOn:
    - name: ${APP}-oidc
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  # Patch only when local dns is used
  # Using postRenderers instead of patches in kustomizations, as variable substitution is not performed already
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              - op: add
                path: /spec/template/spec/hostAliases
                value:
                  - ip: "${traefik_lb_ip}"
                    hostnames:
                    - "${auth_subdomain}.${main_domain}"
                    - "${second_domain}"
            target:
              kind: Deployment
              name: jellyfin
              namespace: media
              annotationSelector: homelab/use-local-dns=true
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
          homelab/use-local-dns: ${quote}${patch_dns:=false}${quote}
        pod:
          priorityClassName: ${gpu_runtime_class}
          runtimeClassName: ${gpu_runtime_class}
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values: ["true"]
        containers:
          jellyfin:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112
            env:
              TZ: Europe/Paris
              JELLYFIN_AutoDiscovery: "false"
              JELLYFIN_LOG_DIR: /logs
              JELLYFIN_DATA_DIR: /data
              JELLYFIN_CONFIG_DIR: /config
              JELLYFIN_CACHE_DIR: /cache
            ports:
              - containerPort: &port ${GATEWAY_SVC_PORT} # 8096
                name: http
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  failureThreshold: 30
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
                nvidia.com/gpu: 1
              limits:
                nvidia.com/gpu: 1
      vue:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          vue:
            image:
              repository: ghcr.io/jellyfin/jellyfin-vue
              tag: unstable.2026-07-03.23ed388@sha256:88cdf369c8ee9dc5c2f462e3d032e3a94f7b80cac42cf4a585136fd78b68d444
            command: ["nginx"]
            args: ["-g", "daemon off;"]
            env:
              TZ: Europe/Paris
            ports:
              - containerPort: &vuePort 80
                name: http
            probes:
              liveness: &vue-probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: http
              readiness: *vue-probes
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true

    service:
      jellyfin:
        controller: jellyfin
        ports:
          http:
            port: *port
      vue:
        controller: vue
        ports:
          http:
            port: *vuePort

    # TODO: enable metrics after upstream PR is merged and released
    # https://github.com/jellyfin/jellyfin/pull/14052
    # serviceMonitor:
    #   jellyfin:
    #     serviceName: jellyfin
    #     endpoints:
    #       - port: http
    #         path: /metrics

    configMaps:
      config:
        forceRename: &vueCm jellyfin-vue-config
        data:
          config.json: |
            {
              "defaultServerURLs": ["https://${SUBDOMAIN}.${DOMAIN_WEBSECURE}"],
              "allowServerSelection": false,
              "routerMode": "history"
            }

    persistence:
      config:
        labels:
          homelab/backup-resource: "true"
        storageClass: ${fastdata_storage}
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          jellyfin:
            jellyfin:
              - path: /config # all config (database.xml, system.xml...)
      config-vue:
        type: configMap
        name: *vueCm
        advancedMounts:
          vue:
            vue:
              - path: /usr/share/nginx/html/config.json
                subPath: config.json
                readOnly: true
      data:
        labels:
          homelab/backup-resource: "true"
        storageClass: ${fastdata_storage}
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          jellyfin:
            jellyfin:
              - path: /data # config includes database, but also metadata

      cache:
        type: "emptyDir"
        advancedMounts:
          jellyfin:
            jellyfin:
              - path: /cache # also include transcodes/
                subPath: cache
      #         - path: /config/metadata
      #           subPath: metadata
      #         - path: /config/data/trickplay
      #           subPath: data/trickplay

      logs:
        type: "emptyDir"
        advancedMounts:
          jellyfin:
            jellyfin:
              - path: /logs
                subPath: logs
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp

      media1:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_media_1}
        advancedMounts:
          jellyfin:
            jellyfin:
              - path: /shared/media1/

      media2:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_media_2}
        advancedMounts:
          jellyfin:
            jellyfin:
              - path: /shared/media2/
      media3:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_media_3}
        advancedMounts:
          jellyfin:
            jellyfin:
              - path: /shared/media3/
      media4:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_media_4}
        advancedMounts:
          jellyfin:
            jellyfin:
              - path: /shared/media4/
      media5:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_media_5}
        advancedMounts:
          jellyfin:
            jellyfin:
              - path: /shared/media5/
      media6:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_media_6}
        advancedMounts:
          jellyfin:
            jellyfin:
              - path: /shared/music/
