---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: jellyfin
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 23.4.1
    digest: sha256:33362d3f0fed1d8321d4ee07d869f6ad0042e5b657892c19c241002bc901881f
  url: oci://oci.trueforge.org/truecharts/jellyfin
