---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: jellyfin
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 23.4.2
    digest: sha256:be2ee367e2227718224085d2a84f22d27e7676aa8665062e8ce54f934313f457
  url: oci://oci.trueforge.org/truecharts/jellyfin
