apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-token
spec:
  data:
    - secretKey: hf_token
      remoteRef:
        key: external-hf-config
        property: hf_token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        HF_TOKEN: "{{ .hf_token }}"
      engineVersion: v2
