---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app atuin
spec:
  releaseName: *app
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      atuin:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/atuinsh/atuin
              tag: 18.17.1@sha256:b2567e0d80a5622dba8d6c5319b198a94ef5166003c2559b91a5406ac688aac7
            args: ["start"]
            env:
              TZ: Europe/Paris
              ATUIN_HOST: 0.0.0.0
              ATUIN_PORT: &port ${GATEWAY_SVC_PORT}
              ATUIN_OPEN_REGISTRATION: false
              ATUIN_CONFIG_DIR: /config
              ATUIN_METRICS__ENABLE: true
              ATUIN_METRICS__HOST: 0.0.0.0
              ATUIN_METRICS__PORT: &metricsPort 8080
              ATUIN_DB_URI:
                secretKeyRef:
                  name: ${PSQL_DB_USER}-db-creds
                  key: uri
              ATUIN_DB_USERNAME:
                secretKeyRef:
                  name: ${PSQL_DB_USER}-db-creds
                  key: username
              ATUIN_DB_PASSWORD:
                secretKeyRef:
                  name: ${PSQL_DB_USER}-db-creds
                  key: password
            ports:
              - containerPort: *port
                name: http
                protocol: TCP
              - containerPort: *metricsPort
                name: metrics
                protocol: TCP
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              limits:
                cpu: 200m
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 50Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      app:
        ports:
          http:
            port: *port
          metrics:
            port: *metricsPort
    serviceMonitor:
      app:
        endpoints:
          - port: metrics
    persistence:
      config:
        type: emptyDir
