---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: atuin
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 7.9.0
    digest: sha256:1feb23eb22930ca19e1d1639d2c9d5092e85b6869d5a8830972e6c75f3dffe30
  url: oci://oci.trueforge.org/truecharts/atuin
