---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app searxng
spec:
  releaseName: *app
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      searxng:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0 # 977
            runAsGroup: 977
            fsGroup: 977
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2026.5.23-323ce7600@sha256:d137e9b7877b7982c5e8ccf878fda0a05d3c8564ebace7f66424a5a19a3c29d9
            env:
              BIND_ADDRESS: "0.0.0.0:8080"
              INSTANCE_NAME: SearXng
              BASE_URL: ""
              SEARXNG_PORT: &port 8080
              SEARXNG_VALKEY_URL: redis://dragonfly-cluster.dragonfly.svc.cluster.local:6379/12
              SEARXNG_SECRET:
                secretKeyRef:
                  name: ${SECRET_KEY_NAME}
                  key: secretKey
            ports:
              - containerPort: *port
                name: http
                protocol: TCP
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                type: TCP
                port: *port

            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
                add: ["CHOWN", "SETGID", "SETUID", "DAC_OVERRIDE"]
    persistence:
      config:
        type: configMap
        name: &configmap searxng-config
        globalMounts:
          - path: /etc/searxng/settings.yml
            subPath: settings.yml
            readOnly: true
          - path: /etc/searxng/limiter.toml
            subPath: limiter.toml
            readOnly: true
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    configMaps:
      config:
        forceRename: *configmap
        data:
          settings.yml: |
            use_default_settings: true
            server:
              limiter: true
              image_proxy: true
              method: GET # https://github.com/searxng/searxng/pull/3619
              public_instance: false
            general:
              instance_name: SearxNG
              privacypolicy_url: false
              donation_url: false
              contact_url: false
              enable_metrics: false
            search:
              safe_search: 0
              autocomplete: duckduckgo
              favicon_resolver: duckduckgo
              autocomplete_min: 2
              languages:
                - all
                - en
                - en-US
                - fr
              formats:
                - html
                - json
              max_page: 0
            ui:
              default_theme: simple
              static_use_hash: true
              infinite_scroll: true
              query_in_title: true
              theme_args:
                simple_style: auto
            enabled_plugins:
              - Basic Calculator
              - Hash plugin
              - Open Access DOI rewrite
              - Search on category select
              - Self Informations
              - Tracker URL remover
              - Unit converter plugin
            hostnames:
              high_priority:
                - (.*)\/blog\/(.*)
                - (.*\.)?wikipedia.org$
                - (.*\.)?github.com$
                - (.*\.)?reddit.com$
                - (.*\.)?docker.com$
                - (.*\.)?archlinux.org$
                - (.*\.)?stackoverflow.com$
                - (.*\.)?askubuntu.com$
                - (.*\.)?superuser.com$
          limiter.toml: |
            [botdetection]

            # The prefix defines the number of leading bits in an address that are compared
            # to determine whether or not an address is part of a (client) network.

            ipv4_prefix = 32
            ipv6_prefix = 48

            trusted_proxies = [
              '127.0.0.0/8',
              '::1',
              '192.168.0.0/16',
              # '172.16.0.0/12',
              '10.0.0.0/8',
              # 'fd00::/8',
            ]


            [botdetection.ip_limit]

            # To get unlimited access in a local network, by default link-lokal addresses
            # (networks) are not monitored by the ip_limit
            filter_link_local = true

            # activate link_token method in the ip_limit method
            link_token = false

            [botdetection.ip_lists]

            # In the limiter, the ip_lists method has priority over all other methods -> if
            # an IP is in the pass_ip list, it has unrestricted access and it is also not
            # checked if e.g. the "user agent" suggests a bot (e.g. curl).

            block_ip = [
            ]

            pass_ip = [
              '192.168.0.0/16',      # IPv4 private network
              '10.0.0.0/8',          # IPv4 private network
            ]

            # Activate passlist of (hardcoded) IPs from the SearXNG organization,
            # e.g. `check.searx.space`.
            pass_searxng_org = false
