---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./namespace.yaml
  - ./onyx/ks.yaml
  - ./toolhive/ks.yaml
  - ./llmkube/ks.yaml
  # - ./vllm/ks.yaml
transformers:
  - ./transformers
components:
  - ../../../common/components/repos/app-template
  - ../../../common/components/repos/authentik-application
  - ../../../common/components/traefik-middlewares
