---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hermes-webui
spec:
  dependsOn:
    - name: hermes
  commonMetadata:
    labels:
      app.kubernetes.io/name: hermes-webui
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: hermes-webui
      namespace: ai
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/oidc-application
    - ../../../../../common/components/httproute/local # common
  path: "./kubernetes/apps/base/ai/hermes-webui/app"
  postBuild:
    substitute:
      APP: hermes-webui
      SUBDOMAIN: hermes-webui
      DOMAIN: ${main_domain}
      DOMAIN_WEBSECURE: ${main_domain_websecure}
      GROUP: Services
      DESCRIPTION: Hermes WebUI
      REDIRECT_URL: https://hermes-webui.${main_domain_websecure}/api/auth/oidc/callback
      ## Gateway
      GATEWAY_SVC_NAME: hermes-webui
      GATEWAY_SVC_PORT: "8787"
      # inherited variables
      auth_subdomain: ${auth_subdomain}
      main_domain: ${main_domain}
      main_domain_websecure: ${main_domain_websecure}
      fastdata_storage: ${fastdata_storage}
  patches:
    - target:
        kind: HelmRelease
        # match with label since name has variable in it
        labelSelector: homelab/auth-component=true
      patch: |
        - op: add
          path: '/spec/values/blueprint/groups/-'
          value:
            slug: "app: hermeswebui"
            parent: "authentik Admins"
            bindID: "8c055d4d-d7ab-4923-ac07-8428dd909c50" # arbitrary uuid
        - op: add
          path: '/spec/values/blueprint/provider/oidc/scopes/-'
          value:
            name: "Hermes Group"
            scope_name: "groups"
            expression: |
              return [group.name for group in user.ak_groups.all()]
              # if ak_is_group_member(request.user, name="app: hermeswebui"):
              #   return ["allowed_user"]
              # return ["none"]
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 10m
