---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: velero
spec:
  dependsOn:
    # Needs monitoring CRDs as it is required by some options
    - name: prometheus-crds
      namespace: opentelemetry
    - name: snapshot-controller
    # - name: s3-instance
    #   namespace: operators
    - name: garage-instance
      namespace: operators
  commonMetadata:
    labels:
      app.kubernetes.io/name: velero
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: velero
      namespace: system-backup
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/garage-bucket
  path: "./kubernetes/platform/base/system-backup/velero/app"
  postBuild:
    substitute:
      S3_USER: ${minio_backup_bucket}
      BUCKET_NAME: ${minio_backup_bucket}
      BUCKET_QUOTA: 100Gi
      GARAGE_URL: garage-gateway.operators.svc.cluster.local:3900 # Same as the secret
      GARAGE_REGION: garage # Same as the secret
      # inherited variables
      minio_url: ${minio_url}
      minio_backup_bucket: ${minio_backup_bucket}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: system-backup
  timeout: 10m
