---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-secrets
spec:
  data:
    - secretKey: renovate_token
      remoteRef:
        key: forgejo-renovate-token
        property: RENOVATE_TOKEN
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: services-secretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        KONFLATE_TOKEN: "{{ .renovate_token }}"
        KONFLATE_WEBHOOK_SECRET: "{{ .renovate_token }}"
        KONFLATE_PUSH_TOKEN: "{{ .renovate_token }}"
        KONFLATE_WRITE_TOKEN: "{{ .renovate_token }}"
      engineVersion: v2
