---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cyberchef
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 14.1.0
    digest: sha256:5b79025c3926175a9a0ac9e38dc353f9f999988d3a1aced2c02f4e8287716154
  url: oci://oci.trueforge.org/truecharts/cyberchef
