---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kavita
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 13.4.0
    digest: sha256:559568995609a836357b2e29a2b6b7aed848eb7e64040d0fdc920e887b42ec6f
  url: oci://oci.trueforge.org/truecharts/kavita
