---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: lidarr
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 29.5.1
    digest: sha256:6552eb10fc7175d58b76571af023f47efe193ebde7b28d1c4e5fd2452b72c21d
  url: oci://oci.trueforge.org/truecharts/lidarr
