# Stack for local GitOps : Forgejo + renovate ?
# This should not be exposed on the Internet
volumes:
  docker_certs:

services:
  # gitea:
  #   # renovate container:
  #   image: docker.io/gitea/gitea:1.24 # -rootless
  #   # userns_mode: "keep-id:uid=1000,gid=1000"
  #   container_name: ${GITEA_INSTANCE_NAME:-local_gitea}
  #   networks:
  #     - dev
  #   volumes:
  #     - ${REPO_PATH:-.}/tmp/gitea/data:/data/gitea:z
  #     - ${REPO_PATH:-.}/tmp/gitea/git:/data/git:z
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   ports:
  #     - 2222:2222/tcp # SSH
  #     - 3000:3000/tcp # Web view
  #   # user: "0"
  #   environment:
  #     - USER_UID=1000
  #     - USER_GID=1000
  #     - DOMAIN=${GITEA_INSTANCE_NAME:-local_gitea}
  #     - SECRET_KEY=secretkey
  #     - GITEA_RUNNER_REGISTRATION_TOKEN=gitearunnertoken123456789123456789 # should be at least 32 characters long

  #     - SSH_EXPOSE_ANONYMOUS=true

  #     - USER=git

  #     - GITEA__database__DB_TYPE=sqlite3
  #     - GITEA__repository_0X2E_pull_0X2D_request__DEFAULT_MERGE_STYLE=rebase
  #   restart: "unless-stopped"

  # gitea-actions:
  #   # renovate container:
  #   image: ghcr.io/vegardit/gitea-act-runner:1.0.8
  #   container_name: local_gitea_actions
  #   networks:
  #     - dev
  #   volumes:
  #     - ${REPO_PATH:-.}/tmp/gitea-runner:/data:z
  #     - /var/run/docker.sock:/var/run/docker.sock:rw
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   # security_opt:
  #   #   - label=disable
  #   #   - seccomp:unconfined
  #   #   - apparmor:unconfined
  #   #   - systempaths=unconfined
  #   #   - unmask=ALL
  #   # cap_add:
  #   #   - NET_ADMIN
  #   #   - SYS_ADMIN
  #   # fuse-overlayfs
  #   # devices:
  #   #   - /dev/fuse
  #   environment:
  #     # https://github.com/vegardit/docker-gitea-act-runner#additional-environment-variables
  #     # - GITEA_RUNNER_UID=1000
  #     # - GITEA_RUNNER_GID=1000
  #     - GITEA_INSTANCE_URL=http://${GITEA_INSTANCE_NAME:-local_gitea}:3000
  #     - GITEA_RUNNER_REGISTRATION_TOKEN=gitearunnertoken123456789123456789
  #     - GITEA_RUNNER_NAME=local_runner
  #     - GITEA_RUNNER_MAX_PARALLEL_JOBS=5 # Tune according to the power of the device
  #     - GITEA_RUNNER_JOB_CONTAINER_NETWORK=dev
  #     # - GITEA_RUNNER_EPHEMERAL=1
  #     # - GITEA_RUNNER_LABELS=
  #   restart: "unless-stopped"

  # Zot for image mirroring
  zot:
    # renovate container:
    image: ghcr.io/project-zot/zot-linux-amd64:v2.1.18
    container_name: zot
    networks:
      - dev
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ${REPO_PATH:-.}/tmp/zot:/tmp/zot:z
      - ${REPO_PATH:-.}/tmp/zot-config.json:/etc/zot/config.json:z
    ports:
      - 15000:15000/tcp # Registry
    restart: "unless-stopped"

  docker-in-docker:
    # renovate container:
    image: data.forgejo.org/oci/docker:dind
    hostname: docker  # Must set hostname as TLS certificates are only valid for docker or localhost
    networks:
      - dev
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_HOST: docker-in-docker
    volumes:
      - docker_certs:/certs

  forgejo:
    # renovate container:
    image: codeberg.org/forgejo/forgejo:15
    container_name: ${FORGEJO_INSTANCE_NAME:-local_forgejo}
    networks:
      - dev
    command: >-
      bash -c '
      /usr/bin/s6-svscan /etc/s6 &
      sleep 10 ;
      su -c "forgejo forgejo-cli actions register --keep-labels --secret ${FORGEJO_RUNNER_SHARED_SECRET}" git ;
      sleep infinity
      '
    environment:
      # Envs from init script
      # FORGEJO_USER_EMAIL: ${FORGEJO_USER_EMAIL}
      # FORGEJO_USERNAME: ${FORGEJO_USERNAME}
      # FORGEJO_PASSWORD: ${FORGEJO_PASSWORD}
      FORGEJO_RUNNER_UUID: ${FORGEJO_RUNNER_UUID}
      FORGEJO_RUNNER_SHARED_SECRET: ${FORGEJO_RUNNER_SHARED_SECRET}
      # Config
      SSH_EXPOSE_ANONYMOUS: "true"
      FORGEJO__security__INSTALL_LOCK: "true"
      FORGEJO__log__LEVEL: "debug"
      DOMAIN: localhost # ${FORGEJO_INSTANCE_NAME:-local_forgejo}
      ROOT_URL: http://localhost:3000
      FORGEJO__repository_0X2E_pull_0X2D_request__DEFAULT_MERGE_STYLE: rebase
      # FORGEJO__repository__ENABLE_PUSH_CREATE_USER: "true"
      # FORGEJO__repository__DEFAULT_PUSH_CREATE_PRIVATE: "false"
      # FORGEJO__repository__DEFAULT_REPO_UNITS: "repo.code,repo.pulls,repo.actions"
    volumes:
      - ${REPO_PATH:-.}/tmp/forgejo:/data
    ports:
      - 3000:3000

  runner-register:
    # renovate container:
    image: data.forgejo.org/forgejo/runner:12.13.0
    networks:
      - dev
    links:
      - docker-in-docker
      - forgejo
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2376
      # FORGEJO_RUNNER_UUID: ${FORGEJO_RUNNER_UUID}
      # FORGEJO_RUNNER_SHARED_SECRET: ${FORGEJO_RUNNER_SHARED_SECRET}
    volumes:
      - ${REPO_PATH:-.}/tmp/forgejo-runner:/data
    user: 0:0
    command: >-
      bash -ec '
      if [ -e config.yml ] ; then echo "config.yml already exists"; exit 0; fi;
      forgejo-runner generate-config > config.yml ;
      sed -i -e "s|  level: info|  level: debug|" config.yml ;
      sed -i -e "s|  capacity: 1|  capacity: 5|" config.yml ;
      sed -i -e "s|  labels: \[\]|  labels: [\"docker-cli:docker://code.forgejo.org/oci/docker:cli\", \"node:docker://code.forgejo.org/oci/node:lts\", \"ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest\", \"ubuntu-24.04:docker://ghcr.io/catthehacker/ubuntu:act-24.04\", \"ubuntu-22.04:docker://ghcr.io/catthehacker/ubuntu:act-22.04\", \"ubuntu-20.04:docker://ghcr.io/catthehacker/ubuntu:act-20.04\"]|" config.yml;
      sed -i -e "s|network: .*|network: host|" config.yml ;
      sed -i -e "s|^  envs:$$|  envs:\n    DOCKER_HOST: tcp://docker:2376\n    DOCKER_TLS_VERIFY: 0\n    DOCKER_CERT_PATH: /certs/client|" config.yml ;
      sed -i -e "s|^  options:|  options: -v /certs/client:/certs/client|" config.yml ;
      sed -i -e "s|  valid_volumes: \[\]$$|  valid_volumes:\n    - /certs/client|" config.yml ;
      sed -i -e "s|  connections:|  connections:\n    default:\n      url: http://forgejo:3000\n      uuid: ${FORGEJO_RUNNER_UUID}\n      token: ${FORGEJO_RUNNER_SHARED_SECRET}|" config.yml ;
      chown -R 1000:1000 /data
      '

  runner-daemon:
    # renovate container:
    image: data.forgejo.org/forgejo/runner:12.13.0
    networks:
      - dev
    links:
      - docker-in-docker
      - forgejo
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "0"
      # FORGEJO_RUNNER_UUID: ${FORGEJO_RUNNER_UUID}
      # FORGEJO_RUNNER_SHARED_SECRET: ${FORGEJO_RUNNER_SHARED_SECRET}
    volumes:
      - ${REPO_PATH:-.}/tmp/forgejo-runner:/data
      - docker_certs:/certs
    restart: unless-stopped
    depends_on:
      - runner-register
    command: >-
      forgejo-runner --config config.yml daemon

networks:
  dev:
    name: dev
    driver: bridge
