---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${CREDS_SECRET_NAME}
spec:
  refreshPolicy: CreatedOnce
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: db-password-generator
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # BULL_AUTH_KEY: "{{ .BULL_AUTH_KEY }}"
        NUQ_DATABASE_PASSWORD: "{{ .password }}"
        NUQ_DATABASE_URL: "postgresql://${PSQL_DB_USER}:{{ .password }}@firecrawl-nuq-postgres.services.svc.cluster.local:5432/${PSQL_DB_NAME}"
        # OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        # SLACK_WEBHOOK_URL: "{{ .SLACK_WEBHOOK_URL }}"
