---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cnpg-barman-cloud
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.0
    digest: sha256:11dc3ca43d20660df7489b9fefbe3c6c140865664f8b0a0a4ef06bda7db0b73a
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/cloudnative-pg/charts.*$"
