---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cnpg-barman-cloud
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.6.0
    digest: sha256:ca5f0e8f5ca7d9c2f436865a0bd62626c4fa4eb39a6326db55780f38a56342f3
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/cloudnative-pg/charts.*$"
