apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: karakeep-cors-headers
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
    accessControlAllowOriginListRegex:
      - ".*://([a-z]*\\.)?${main_domain}"
      # Karakeep specific
      - "chrome-extension://kgcjekpmcjjogibpjebkhaanilehneje"
      - "moz-extension://739b0e68-bf1f-49a8-9a11-ef362c1468cc"
    accessControlAllowHeaders:
      - Authorization
      - Content-Type
    accessControlAllowCredentials: true
    accessControlMaxAge: 3600
