---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: firecrawl
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: firecrawl
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: firecrawl
      namespace: services
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/secret/key
  path: "./kubernetes/apps/base/services/firecrawl/app"
  postBuild:
    substitute:
      APP: firecrawl
      CREDS_SECRET_NAME: firecrawl-creds
      PSQL_DB_USER: postgres
      PSQL_DB_NAME: postgres
      ## API key
      SECRET_KEY_NAME: firecrawl-bull-key
      SECRET_KEY_TYPE: 64hexa
      # GATEWAY_SVC_NAME: firecrawl
      # GATEWAY_SVC_PORT: "8000"
      # inherited variables
      fastdata_storage: ${fastdata_storage}

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: services
  timeout: 10m
