# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: obsidian
spec:
  alias: obsidian
  url: http://obsidian-livesync.services.svc.cluster.local:8787/mcp
  transport: http
