---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: csi-proxmox
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.5.9
    digest: sha256:824b521aec40da8f44e6c0cbd0436dafc884a8a8becd8d13447f586084a7d521
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin