---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: csi-proxmox
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.5.8@sha256:0f402c014900573e84160b9538ba220d6476f0198b30cd2182cf8e988296c34a
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin