---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prowlarr
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 22.5.0
    digest: sha256:5529d1ec033bf8ed281a73a08766c8f5cc5767d343b14550195577bd8cd0c91c
  url: oci://oci.trueforge.org/truecharts/prowlarr
