---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prowlarr
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 22.5.1
    digest: sha256:50245d98f7c148c3b3c7a067d9ca95fbc96508eb8db1050523ff03a49ce879c5
  url: oci://oci.trueforge.org/truecharts/prowlarr
