---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prowlarr
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 22.3.0
    digest: sha256:cd9ed36ce0dc7e5e7fe2376a76b39d56d6107a2987ab952beab6428ded40a116
  url: oci://oci.trueforge.org/truecharts/prowlarr
