---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-operator-crds
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.1
    digest: sha256:7b2308ad23e54537b428d8d629ab61c39618bf7c9733f8426562f8a392322e0d
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator-crds
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/VictoriaMetrics/helm-charts.*$"
