---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-operator-crds
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.12.0
    digest: sha256:b286c8dae2cae69fc6a6384045b61af9f7928e3deb00f9bb6aa9690c538e4dbf
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator-crds
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/VictoriaMetrics/helm-charts.*$"
