---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-operator-crds
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.14.0
    digest: sha256:ade14ed15fd3e4f5329940713c81265ee52047496ac5662edea2ada418f6737b
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator-crds
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/VictoriaMetrics/helm-charts.*$"
