---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: velero
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 12.2.0
    digest: sha256:8dd8ecee7ae3ba10101e8b0b5b3bd3fd917efd938d449ffeebec81799c02e46c
  url: oci://ghcr.io/vmware-tanzu/charts/velero
