---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: velero
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 12.1.0
    digest: sha256:c1ba5267dc85b7f6bba4d836c87d31500a1b9aee1cef1cf3eaa4229b251d86d7
  url: oci://ghcr.io/vmware-tanzu/charts/velero
