apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-store-kubernetes-ns
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-store-kubernetes-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: velero-store-kubernetes-ns
subjects:
  - kind: ServiceAccount
    name: velero-store-kubernetes-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-store-kubernetes-ns
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: velero-store
spec:
  provider:
    kubernetes:
      remoteNamespace: system-backup
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: velero-store-kubernetes-ns
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-aws-creds-file
spec:
  data:
    - secretKey: accessKey
      remoteRef:
        key: ${S3_USER}-garage
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        key: ${S3_USER}-garage
        property: secretKey
    - secretKey: region
      remoteRef:
        key: ${S3_USER}-garage
        property: region
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: velero-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        # https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/README.md
        # https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html
        cloud: | # default
          [default]
          aws_access_key_id = {{ .accessKey }}
          aws_secret_access_key = {{ .secretKey }}
          region = {{ .region }}
      engineVersion: v2
