storage:
  size: 1Gi

mariadb:
  enableAntiAffinity: true
  image:
    repository: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator
    tag: 26.10.0@sha256:3be6c0fb8094e67f9d65eebfb240cd89741098632c1ed69c281445a39621562c
