apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: papra-store-kubernetes-ns
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: papra-store-kubernetes-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: papra-store-kubernetes-ns
subjects:
  - kind: ServiceAccount
    name: papra-store-kubernetes-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: papra-store-kubernetes-ns
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: papra-store
spec:
  provider:
    kubernetes:
      remoteNamespace: services
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: papra-store-kubernetes-ns
