---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bentopdf
spec:
  releaseName: *app
  dependsOn:
    - name: ${APP}-proxy
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      bentopdf:
        containers:
          app:
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true # Entrypoints does modifications in /etc/nginx
              capabilities: { drop: ["ALL"] }
            image:
              repository: ghcr.io/alam00000/bentopdf-simple
              tag: 2.8.6@sha256:1a947a9d4ae515be27b381a2a1f8565d5fa33087c32abc2bb7a6754f83e95f4c
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
            ports:
              - containerPort: &port ${GATEWAY_SVC_PORT}
                name: http
                protocol: TCP
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 50M
              limits:
                memory: 512Mi
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
            subPath: cache
          - path: /etc/nginx/tmp
            subPath: etc-tmp
          - path: /var/lib/nginx/tmp
            subPath: var-tmp
    service:
      app:
        controller: bentopdf
        ports:
          http:
            port: *port
