---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bentopdf
spec:
  releaseName: *app
  dependsOn:
    - name: ${APP}-proxy
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    controllers:
      bentopdf:
        containers:
          main:
            securityContext:
              capabilities:
                drop:
                  - ALL
            image:
              repository: ghcr.io/alam00000/bentopdf
              tag: 2.8.6@sha256:eaeea1e447205a79cb61d7efdc6966f37311dc1bc9c36a3a5c897bf79107c2c3
              pullPolicy: IfNotPresent
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 200M
              limits:
                memory: 1Gi
    service:
      app:
        controller: bentopdf
        ports:
          http:
            port: ${GATEWAY_SVC_PORT}
