---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flaresolverr
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 17.5.0
    digest: sha256:06f0a8fc564bc30fead390600b5066087ddcd85bb3ebcf99e14e6c8a9767d2a6
  url: oci://oci.trueforge.org/truecharts/flaresolverr
