apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: ${PSQL_RO_USER}
spec:
  cluster:
    name: ${psql_cluster_name}
  name: ${PSQL_RO_USER}
  ensure: present
  comment: "${PSQL_RO_USER} read-only user for app ${APP}"
  login: true
  superuser: false
  createdb: false
  databaseRoleReclaimPolicy: delete
  # inRoles:
  #   - pg_monitor
  passwordSecret:
    name: ${PSQL_RO_USER}-db-creds
