apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tachi-external-secrets
spec:
  data:
    - secretKey: captchaToken
      remoteRef:
        key: external-tachi-config
        property: captcha_token
    - secretKey: cdnWebLocation
      remoteRef:
        key: external-tachi-config
        property: cdn_web_location
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        captcha_token: "{{ .captchaToken }}"
        cdn_web_location: "{{ .cdnWebLocation }}"
      engineVersion: v2
