---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tachi
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: apollo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tachi
      namespace: otoge
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/cnpg/db
    - ../../../../../common/components/garage-bucket # In the future
    - ../../../../../common/components/secret/key # Session secret
    # - ../../../../../common/components/secret/key2
    # - ../../../../../common/components/secret/creds
  path: "./kubernetes/apps/base/otoge/tachi/app"
  postBuild:
    substitute:
      # Must also set the following in platform/base/internal-ci/tekton-pipelines/app/helmrelease.yaml
      APP: tachi
      SUBDOMAIN: xn--sck3h9451a
      DOMAIN: ${second_domain}
      DOMAIN_WEBSECURE: ${second_domain_websecure}
      # S3
      S3_USER: tachi-${environment}
      BUCKET_NAME: tachi-${environment}
      GARAGE_URL: garage-gateway.operators.svc.cluster.local:3900 # Same as the secret
      GARAGE_REGION: garage # Same as the secret
      # BUCKET_QUOTA: 20Gi
      ## Database
      PSQL_DB_USER: tachi
      PSQL_DB_NAME: tachi
      # uuid-ossp pgcrypto pg_trgm
      DATABASE_EXTENSIONS: |
        [
          { name: pg_stat_statements, ensure: present },
          { name: pg_partman_bgw, ensure: present }
        ]
      ## API key
      SECRET_KEY_NAME: tachi-session-secret
      SECRET_KEY_TYPE: secret-key
      # inherited variables
      psql_cluster_name: ${psql_cluster_name}
      psql_database_namespace: ${psql_database_namespace}
      main_domain: ${main_domain}
      main_domain_websecure: ${main_domain_websecure}
      second_domain: ${second_domain}

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: otoge
  timeout: 10m
