---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2026.5.5
    digest: sha256:aaaadfa0fc1b0db1520fb93f6a8e4ba56e699b16e5d63f85be47a1933532beaf
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
