---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2026.8.3
    digest: sha256:9c36fde86366feede3252292890a8cc0cf3a299ecb2faa03d783944f834dd28b
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
