---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2026.5.6
    digest: sha256:0c9cac0aac7b3c4f947e2f134340f753d03e2e1bb9b057ec20b249788aef6fda
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
