---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  releaseName: *app
  dependsOn:
    - name: ${APP}-proxy
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      *app :
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
            env:
              LOG_LEVEL: debug
              FIREWALL: "on"
              FIREWALL_OUTBOUND_SUBNETS: "192.168.1.0/24,192.168.128.0/24,10.24.0.0/16" # Local network, ingress cidr, pod cidr (svc cidr ?)
              VPN_TYPE: "wireguard"
              VPN_SERVICE_PROVIDER: "protonvpn"
              WIREGUARD_PRIVATE_KEY:
                secretKeyRef:
                  name: gluetun-config
                  key: private_key
              # WIREGUARD_ENDPOINT_PORT: 51820
              SERVER_COUNTRIES: "Netherlands,Switzerland"
              DNS_UPSTREAM_RESOLVER_TYPE: "dot"
              DNS_UPSTREAM_RESOLVERS: "cloudflare,google"
              DOT: "on"
              BLOCK_MALICIOUS: "off"
              PORT_FORWARD_ONLY: "on"
              VPN_PORT_FORWARDING: "on"
              # https://www.reddit.com/r/gluetun/comments/1kpbfs2/the_definitive_howto_for_setting_up_protonvpn/?show=original
              VPN_PORT_FORWARDING_UP_COMMAND: /bin/sh -c 'wget -O- --retry-connrefused
                --post-data "json={\"listen_port\":{{ `{{PORTS}}` }}}"
                http://127.0.0.1:${GATEWAY_SVC_PORT}/api/v2/app/setPreferences 2>&1'
              # HTTP Proxy (for indexer)
              HTTPPROXY: "on"
              FIREWALL_INPUT_PORTS: ${GATEWAY_SVC_PORT},8888
              #optional
              HTTPPROXY_LOG: "off" # "on" for debug
              HTTPPROXY_LISTENING_ADDRESS: :8888
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              privileged: true
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false # true
              capabilities: { drop: ["ALL"], add: ["NET_ADMIN", "CHOWN"] }
            resources:
              requests:
                cpu: 50m
                memory: 50Mi
              limits:
                memory: 100Mi
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.2.3@sha256:4fcf15b7f265c2c8d7bc2a7e13240a07e0593c326f3cf3b5b9bb69eec5b79299
            env:
              TZ: Europe/Paris
              QBT_WEBUI_PORT: &port 8080
              QBT_TORRENTING_PORT: &torrentPort 6881
            ports:
              - containerPort: *port
                name: main
                protocol: TCP
              - containerPort: &gluetunPort 8888
                name: gluetun
                protocol: TCP
              - containerPort: *torrentPort
                name: torrent
                protocol: TCP
              - containerPort: *torrentPort
                name: torrentudp
                protocol: UDP
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                type: TCP
                port: *port
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 500Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
          gluetun:
            port: *gluetunPort
          torrent:
            port: *torrentPort

    persistence:
      config:
        labels:
          homelab/backup-resource: "true"
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ${fastdata_storage}-ha
        globalMounts:
          - path: /config
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
      downloads:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_download}
        globalMounts:
          - path: /downloads
