---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  releaseName: qbittorrent
  dependsOn:
    - name: ${APP}-proxy
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3
  # see https://github.com/truecharts/public/blob/master/charts/stable/qbittorrent/values.yaml
  values:
    # Gluetun setup
    # https://trueforge.org/truetech/truecharts/guides/addons/vpn-setup/
    addons:
      gluetun:
        enabled: true
        container:
          env:
            FIREWALL: "on"
            FIREWALL_OUTBOUND_SUBNETS: "192.168.1.0/24,192.168.128.0/24,10.24.0.0/16" # Local network, ingress network, kubernetes network
            VPN_TYPE: "wireguard"
            VPN_SERVICE_PROVIDER: "protonvpn"
            WIREGUARD_PRIVATE_KEY:
              secretKeyRef:
                name: gluetun-config
                key: private_key
                expandObjectName: false
            SERVER_COUNTRIES: "Netherlands,Swiss"
            PORT_FORWARD_ONLY: "on"
            VPN_PORT_FORWARDING: "on"
            # HTTP Proxy (for indexer)
            HTTPPROXY: "on"
            FIREWALL_INPUT_PORTS: 10095,8888
            #optional
            HTTPPROXY_LOG: "off" # "on" for debug
            HTTPPROXY_LISTENING_ADDRESS: :8888
    service:
      proxy:
        enabled: true
        ports:
          gluetun:
            enabled: true
            port: 8888
            protocol: "http"
            targetPort: 8888
        type: "ClusterIP"
    # workload:
    #   main:
    #     podSpec:
    #       containers:
    #         main:
    #           env:
    #             QBT_DOWNLOADS_PATH: /downloads/complete
    #             QBT_TEMP_PATH: /downloads/incomplete
    #             QBT_TORRENT_PATH: /downloads/torrent
    #             TZ: Europe/Paris
    #             PUID: 1000 # User ID, should have the rights on the NFS share and the dataset
    #             PGID: 1000 # Group ID
    persistence:
      config:
        enabled: true
        labels:
          homelab/backup-resource: "true"
        type: pvc
        size: 1Gi
        storageClass: ${fastdata_storage}-ha
        mountPath: /config
      downloads:
        enabled: true
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_download}
        mountPath: /downloads
