---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: qbittorrent
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 25.4.3
    digest: sha256:28655f8dfdab48c608c7e472d7429db72a48cea6866fe386c5c5a101f80d08b7
  url: oci://oci.trueforge.org/truecharts/qbittorrent
