---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  releaseName: renovate-operator
  dependsOn:
    - name: ${APP}-oidc
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3
    crds: CreateReplace
    strategy:
      name: RetryOnFailure # retry failed upgrades instead of rollback
      retryInterval: 5m
  upgrade:
    crds: CreateReplace

  valuesFrom:
    - kind: Secret
      name: ${APP}-oidc-authentik-application
      valuesKey: clientID
      targetPath: auth.oidc.clientId
    - kind: Secret
      name: ${APP}-oidc-authentik-application
      valuesKey: issuerURL
      targetPath: auth.oidc.issuerUrl
    - kind: Secret
      name: ${APP}-oidc-authentik-application
      valuesKey: redirectURL
      targetPath: auth.oidc.redirectUrl
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              - op: add
                path: /spec/template/spec/hostAliases
                value:
                  - ip: "${traefik_lb_ip}"
                    hostnames:
                    - "${auth_subdomain}.${main_domain}"
                    - "${second_domain}"
            target:
              kind: Deployment
              name: renovate-operator
              annotationSelector: homelab/use-local-dns=true
  values:
    # https://github.com/mogenius/renovate-operator/blob/main/charts/renovate-operator/values.yaml
    fullnameOverride: "renovate-operator"
    crd:
      install: true
      mode: template

    webhook:
      enabled: true

    config:
      logStorage:
        mode: valkey
    extraEnv:
      - name: VALKEY_URL
        value: redis://dragonfly-cluster.dragonfly.svc.cluster.local:6379/5
    auth:
      oidc:
        enabled: true
        # issuerUrl:   # valuesFrom
        # redirectUrl:   # valuesFrom
        # clientId:    # valuesFrom
        existingSecret: ${APP}-oidc-authentik-application
        secretKey: clientSecret
        fetchUserInfoGroups: true

    rbac:
      ownNamespaceOnly: false # If own namespace, it creates a serviceAccount which does not have the permission to patch jobs

    valkey:
      enabled: false

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      dashboard:
        enabled: true
        # Default values force the use of the label grafana.internal/instance: "grafana"
        # see https://github.com/mogenius/renovate-operator/issues/485
        grafanaDashboard:
          allowCrossNamespaceImport: true
          instanceSelector:
            matchLabels:
              dashboards: grafana
          resyncPeriod: 30s
          datasources:
            - datasourceName: Metrics as prometheus
              inputName: DS_PROMETHEUS
    telemetry:
      enabled: true
      endpoint: "opentelemetry-kube-stack-daemon-collector.opentelemetry.svc.cluster.local:4317"
      protocol: grpc
      forwardToJobs: true
