---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vaultwarden
spec:
  releaseName: *app
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      priorityClassName: services-important
    controllers:
      vaultwarden:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          waitpsql:
            enabled: true
            image:
              repository: ghcr.io/home-operations/busybox
              tag: 1.38.0@sha256:7e2c04dd50ede647bf4a7a4c8dbd629dd4971cd139b9b88fb22bfc3c7a6c13df
              pullPolicy: IfNotPresent
            command:
              [
                "sh",
                "-c",
                'until nc -vz $${POD_NAME}.$${POD_NAMESPACE}.svc.cluster.local 5432; do echo "Waiting for postgres..."; sleep 3; done;',
              ]
            env:
              POD_NAME: postgres-db-rw # service name for psql rw operations
              POD_NAMESPACE: ${psql_database_namespace}
        containers:
          app:
            image:
              repository: vaultwarden/server
              tag: 1.36.0@sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
            env:
              ADMIN_TOKEN:
                secretKeyRef:
                  name: ${SECRET_KEY_NAME}
                  key: secretKey
              DOMAIN: "https://${SUBDOMAIN}.${DOMAIN_WEBSECURE}"
              TZ: Europe/Paris
              DATABASE_URL:
                secretKeyRef:
                  name: ${PSQL_DB_USER}-db-creds
                  key: uri
              LOG_LEVEL: trace
              EXTENDED_LOGGING: true
              INVITATIONS_ALLOWED: true
              ORG_CREATION_USERS: all
              REQUIRE_DEVICE_EMAIL: false
              ENABLE_DB_WAL: false # As we use sqlite
              ROCKET_PORT: &port ${GATEWAY_SVC_PORT}
              SHOW_PASSWORD_HINT: false
              SIGNUPS_ALLOWED: false
              SIGNUPS_VERIFY: false
              WEBSOCKET_ENABLED: true
              WEB_VAULT_ENABLED: true
              SMTP_HOST:
                secretKeyRef:
                  name: smtp-config
                  key: smtp_server
              SMTP_PORT:
                secretKeyRef:
                  name: smtp-config
                  key: smtp_port
              SMTP_FROM:
                secretKeyRef:
                  name: smtp-config
                  key: smtp_username
              SMTP_USER:
                secretKeyRef:
                  name: smtp-config
                  key: smtp_username
              SMTP_PASSORD:
                secretKeyRef:
                  name: smtp-config
                  key: smtp_token
              SMTP_SECURITY: "starttls"
            ports:
              - containerPort: *port
                name: http
                protocol: TCP
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 100Mi
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ${fastdata_storage}-ha
