apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onyx-userauth
  labels:
    homelab/backup-resource: "true"
spec:
  refreshPolicy: CreatedOnce
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: 64hexa

  target:
    template:
      metadata:
        labels:
          homelab/backup-resource: "true"
      data:
        secretKey: "{{ .password }}"
      engineVersion: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onyx-sandbox-push-secret
  labels:
    homelab/backup-resource: "true"
spec:
  refreshPolicy: CreatedOnce
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: ssh-ed25519

  target:
    template:
      metadata:
        labels:
          homelab/backup-resource: "true"
      # Populates privateKey and publicKey fields containing the SSHKey pair
