---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: onyx
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.8.25
    digest: sha256:47c04107b34c0fb180c755182559ceae09390f6572723d3f7aa75479268be8d8
  url: oci://ghcr.io/onyx-dot-app/charts/onyx
