---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName ${PSQL_RO_USER}-db-creds
spec:
  refreshPolicy: OnChange
  dataFrom:
    - extract:
        key: *secretName
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres-secrets
  target:
    # name: ${APP}-db-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/cluster: ${psql_cluster_name}
          cnpg.io/reload: "true"
