---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: grafana-mcp
  namespace: monitoring # Create the resource directly in the namespace
spec:
  image: docker.io/grafana/mcp-grafana:0.14.0-alpine@sha256:59d48eab68e915e01660fb2666d46a9664b37cd9e93fdcc4babeb2779fa3f35b
  args: [ "-t", "stdio" ]
  transport: stdio
  # groupRef:
  #   name: mcp-tools
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.monitoring.svc.cluster.local:3000
  secrets:
    - name: grafana-mcp
      key: token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
  podTemplateSpec:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mcp
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "10m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: [ "ALL" ] }
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi
