---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nvidia-system
resources:
  - ./namespace.yaml
  - ./nvidia-gpu-operator/ks.yaml
transformers:
  - ./transformers
