---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: minio
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 17.4.0
    digest: sha256:d358d7a170d59b99190f732f8ecc64ec0b7c463e83cac9915c0b74daf3ce2928
  url: oci://oci.trueforge.org/truecharts/minio