---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: minio
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 17.6.0
    digest: sha256:62f06e0e661b95b2271ff0bd86da0bf4c3b097fd4e58a9357fe4c27f4c807db2
  url: oci://oci.trueforge.org/truecharts/minio