image:
  repository: ghcr.io/muety/wakapi
  pullPolicy: IfNotPresent
  tag: "2.17.4@sha256:6fce764acf8775e1166e8b03e59fb6b34744e4a9fba5e98d9ea15d341db31bf8"

config:
  port: 3000
  db:
    host: localhost
    port: 5432
    name: wakapi
    user: wakapi
  public_url: http://localhost:3000
  insecure_cookies: false
  allow_signup: true
  export_metrics: false

resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 100m
    memory: 100Mi

backupLabel:
  homelab/backup-resource: "true"