image:
  repository: ghcr.io/muety/wakapi
  pullPolicy: IfNotPresent
  tag: "2.17.3@sha256:156e3e60656f6143f58cc849444a0a7992bbaa573dc870d92a9789be5671099d"

config:
  port: 3000
  db:
    host: localhost
    port: 5432
    name: wakapi
    user: wakapi
  public_url: http://localhost:3000
  insecure_cookies: false
  allow_signup: true
  export_metrics: false

resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 100m
    memory: 100Mi

backupLabel:
  homelab/backup-resource: "true"