---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 41.0.1
    digest: sha256:394b7c78c44f275f8562ab653b7cab8dc3014bc7af52220204fe4fd8251884ca
  url: oci://ghcr.io/traefik/helm/traefik
