---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 40.2.0
    digest: sha256:582cafe24846a332e7c7fcb9a5f9ba2cb906aa17a7cf431e1cdaa6c0ac986397
  url: oci://ghcr.io/traefik/helm/traefik
