---
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: qwen36-35b-a3b-iq2-m
spec:
  # source: https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/resolve/main/Qwen3.6-35B-A3B-UD-IQ3_S.gguf
  source: https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/resolve/main/Qwen3.6-35B-A3B-UD-IQ2_M.gguf
  format: gguf
  quantization: IQ2_M
  hardware:
    accelerator: cuda
    gpu:
      enabled: true
      vendor: nvidia
      count: 1
      # layers: 20
    #   memory: 14Gi
    # memoryBudget: 14Gi
  resources:
    cpu: "6"
    memory: 16Gi
---
apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: qwen36-35b-a3b
spec:
  modelRef: qwen36-35b-a3b-iq2-m
  runtimeClassName: ${gpu_runtime_class}
  runtime: llamacpp
  # https://github.com/ggml-org/llama.cpp/pkgs/container/llama.cpp/versions?filters[version_type]=tagged
  image: ghcr.io/ggml-org/llama.cpp:server-cuda13-b9191
  # https://github.com/ikawrakow/ik_llama.cpp/pkgs/container/ik-llama-cpp/versions?filters[version_type]=tagged
  # image: ghcr.io/ikawrakow/ik-llama-cpp:cu13-server-4535
  # Wait more official fork btw https://github.com/turbo-tan/llama.cpp-tq3
  # image: dexogen/atomic-llama-cpp-turboquant:cuda13 # required for TQ3_4S
  replicas: 1
  endpoint:
    port: 8080
    type: ClusterIP
  priority: high
  evictionProtection: false
  contextSize: 32768 # -c
  flashAttention: true # -fa
  parallelSlots: 1 # -np
  cacheTypeCustomK: q8_0
  cacheTypeCustomV: q8_0
  batchSize: 2048 # -b
  uBatchSize: 512 # -ub
  # moeCPULayers: 20
  # moeCPUOffload: true # Offload all expert layers to CPU

  noKvOffload: false # KV in RAM instead of VRAM
  reasoningBudget: 512  # Necessary for models like Qwen
  # skipModelInit:
  # tensorOverrides:
  nodeSelector:
    nvidia.com/gpu.present: "true"
  env:
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          name: hf-token
          key: HF_TOKEN
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 101 # curl_user
    seccompProfile:
      type: RuntimeDefault
  # priorityClassName:
  extraArgs:
    # https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md
    # https://github.com/ikawrakow/ik_llama.cpp/blob/main/docs/parameters.md
    - --spec-type
    - "draft-mtp"
    - --spec-draft-n-max
    - "2"
    - --jinja
    - --ctx-checkpoints
    - "128"
    - --temp
    - "1.0"
    - --top-p
    - "0.95"
    - --min-p
    - "0.00"
    - --presence-penalty
    - "1.5"
    - --repeat-penalty
    - "1.0"
    - --top-k
    - "20"
    - --fit
    - "on"
    - --chat-template-kwargs
    - '{"preserve_thinking": true}'
    # ik_llama specific settings
    # - --defer-experts
    # - --spec-type
    # - mtp
    # - -mtp
    # - --draft-max
    # - "2"

  # podLabels:
  #   app.kubernetes.io/name: llmkube
  # podAnnotations:
  #   sidecar.istio.io/inject: "true"
  resources:
    gpu: 1
    cpu: "2"
    gpuMemory: 14Gi
    hostMemory: 12Gi
    memory: 16Gi
