apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Namespace }}-secretstore
spec:
  provider:
    kubernetes:
      remoteNamespace: &ns {{ .Release.Namespace }}
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: *ns
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ .Release.Namespace }}-secretstore
          namespace: *ns
