---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-github-http-creds
spec:
  data:
    # - secretKey: identity
    #   remoteRef:
    #     key: external-github-sa
    #     property: identity
    # - secretKey: known_hosts
    #   remoteRef:
    #     key: external-github-sa
    #     property: known_hosts
    # - secretKey: githubAppID
    #   remoteRef:
    #     key: external-github-sa
    #     property: githubAppID
    # - secretKey: githubAppInstallationID
    #   remoteRef:
    #     key: external-github-sa
    #     property: githubAppInstallationID
    # - secretKey: githubAppPrivateKey
    #   remoteRef:
    #     key: external-github-sa
    #     property: githubAppPrivateKey
    - secretKey: username
      remoteRef:
        key: external-github-sa
        property: username
    - secretKey: password
      remoteRef:
        key: external-github-sa
        property: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        # githubAppID: "{{ .githubAppID }}"
        # githubAppInstallationID: "{{ .githubAppInstallationID }}"
        # githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
      engineVersion: v2
