---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gitea
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 12.6.0
    digest: sha256:0c1259446b61564cc73ef0d87edc6d9cc00ccc137b8f76be26d317ea44c0fcc3
  url: oci://docker.gitea.com/charts/gitea
