---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellystat
spec:
  releaseName: *app
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      jellystat:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          waitpsql:
            enabled: true
            image:
              repository: ghcr.io/home-operations/busybox
              tag: 1.38.0@sha256:7e2c04dd50ede647bf4a7a4c8dbd629dd4971cd139b9b88fb22bfc3c7a6c13df
              pullPolicy: IfNotPresent
            command: ["sh", "-c", 'until nc -vz $${POD_NAME}.$${POD_NAMESPACE}.svc.cluster.local 5432; do echo "Waiting for postgres..."; sleep 3; done;']
            env:
              POD_NAME: postgres-db-rw # service name for psql rw operations
              POD_NAMESPACE: ${psql_database_namespace}
        containers:
          app:
            image:
              repository: cyfershepard/jellystat
              tag: 1.1.11@sha256:c4e2dfa8bddf8d5ac3a675d7202f71a54dcfe3540cc186899d9201e0fe701fa5
            env:
              POSTGRES_DB: ${PSQL_DB_NAME}
              POSTGRES_USER: ${PSQL_DB_USER}
              POSTGRES_PASSWORD:
                secretKeyRef:
                  name: ${APP}-db-creds
                  key: password
              POSTGRES_IP: "postgres-db-rw.${psql_database_namespace}.svc.cluster.local"
              POSTGRES_PORT: "5432"
              JWT_SECRET:
                secretKeyRef:
                  name: ${SECRET_KEY_NAME}
                  key: secretKey
              JS_USER:
                secretKeyRef:
                  name: ${SECRET_CREDS_NAME}
                  key: username
              JS_PASSWORD:
                secretKeyRef:
                  name: ${SECRET_CREDS_NAME}
                  key: password
            ports:
              - containerPort: &port 3000
                name: http
                protocol: TCP
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              limits:
                cpu: 500m
                memory: 250Mi
              requests:
                cpu: 10m
                memory: 100Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
