---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: jellystat
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 7.4.1
    digest: sha256:f1fda058626a91aecc611ab34725f0e75af82182dd9dbc17dc0a7fe165eb4b3e
  url: oci://oci.trueforge.org/truecharts/jellystat
