---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 32.0.0
    digest: sha256:676add1a5db4dc52af87e94d2b7a5831a39fc8d95036a51e5361b7b17a9c3f46
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
