---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 29.0.0
    digest: sha256:36bab74f99bb3c3a1ab7003b8ab8651592fab7563067294336d2706e2dba137f
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
