---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: memini
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v0.7.18
    digest: sha256:2a4e1434c81611d3b3891b36f6d64a0876dfcae7a6bc118cb46bdb8111b3a2f9
  url: oci://registry.erwanleboucher.dev/eleboucher/charts/memini
