---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.66.2
    digest: sha256:a875b8002b4bcff53640a5a609a46ed6f5e638ee923dfbd67765ebf59bd9bf89
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/VictoriaMetrics/helm-charts.*$"
