---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: garage-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 0.6.22
    digest: sha256:fb5f1a9b1737838ec9df0314b302c5366f73ec52e877ab9332db8c2fb84dad18
  url: oci://ghcr.io/rajsinghtech/charts/garage-operator
