---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: garage-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 0.6.28
    digest: sha256:52e7e66658bc03479a758e4f5abdf103820a954b958cac62df1ef87b479829d4
  url: oci://ghcr.io/rajsinghtech/charts/garage-operator
