---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: garage-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 0.6.12
    digest: sha256:cac3ad557af29f29b8e0152fef5954febb6747ff64dd553c6c695a5dc5623b25
  url: oci://ghcr.io/rajsinghtech/charts/garage-operator
