apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-external-secret
spec:
  data:
    - secretKey: garage_admin_token
      remoteRef:
        key: external-garage-secrets
        property: garage_admin_token
    - secretKey: garage_rpc_secret
      remoteRef:
        key: external-garage-secrets
        property: garage_rpc_secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        GARAGE_ADMIN_TOKEN: "{{ .garage_admin_token }}"
        GARAGE_RPC_SECRET: "{{ .garage_rpc_secret }}"
      engineVersion: v2
