---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.0.19
    digest: sha256:8fb437bcf4477daa02ca4f2d0c0c6ac29847b2b1aa7cf016656159c813a950ec
  url: oci://ghcr.io/home-operations/charts/litellm-operator
