---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.0.9
    digest: sha256:0c92bf42542af90be6ab3a8df6ea22de5a270671661c4419f4776ff8f22dd2e9
  url: oci://ghcr.io/home-operations/charts/litellm-operator
