---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jdownloader2
spec:
  releaseName: *app
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        # fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      jdownloader2:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
        containers:
          app:
            image:
              repository: ghcr.io/jlesage/jdownloader-2
              tag: v26.03.1@sha256:3d6cb102bd9bacff12ab1ca5136a38cb8f93d6595a7ccf5bce60aac4df138ebd
            env:
              DARK_MODE: 1
              DISPLAY_WIDTH: 1680
              DISPLAY_HEIGHT: 800
              KEEP_APP_RUNNING: "0"
              SECURE_CONNECTION: "0"
              ENABLE_CJK_FONT: "0"
              VNC_PASSWORD: ""

            resources:
              limits:
                memory: 800Mi
              requests:
                cpu: 100m
                memory: 400Mi
            ports:
              - containerPort: &port ${GATEWAY_SVC_PORT}
                name: http
                protocol: TCP
              - containerPort: &vncPort 5900
                name: vnc
                protocol: TCP
              - containerPort: &myjdPort 3129
                name: myjd
                protocol: TCP
            probes:
              liveness: &probes
                enabled: true
                type: TCP
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              # readOnlyRootFilesystem: false
              # capabilities:
              #   drop: ["ALL"]
              #   add: ["KILL", "NET_BIND_SERVICE"]

    service:
      app:
        controller: jdownloader2
        ports:
          http:
            port: *port
          vnc:
            port: *vncPort
          myjd:
            port: *myjdPort

    persistence:
      config:
        type: emptyDir
      output:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_download}
        globalMounts:
          - path: /output
