---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: jdownloader2
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 22.4.0
    digest: sha256:c099e5a3502ccb1bbe568d853bf733beb5e7c665fbcfb60534ab85a6ec02a45e
  url: oci://oci.trueforge.org/truecharts/jdownloader2
