---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${PSQL_DB_USER}-db-creds
spec:
  refreshPolicy: CreatedOnce # TODO : We may allow periodic rotation once reloader is set on pods
  # refreshPolicy: Periodic
  # refreshInterval: "1h"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: db-password-generator

  target:
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "${PSQL_DB_USER}"
        password: "{{ .password }}"
      engineVersion: v2
