---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-external-sources
spec:
  dataFrom:
    - extract:
        key: external-sources-secrets
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: renovate-external-sources
    creationPolicy: Owner
    deletionPolicy: Retain
