---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: &name grafana-mcp
spec:
  name: *name
  instanceName: grafana
  role: Editor
  isDisabled: false
  tokens:
    - name: mcp
      secretName: *name
