---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app suwayomi
spec:
  releaseName: *app
  chartRef:
    kind: OCIRepository
    name: *app
  maxHistory: 2
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      suwayomi:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v2.3.2232@sha256:553eb2db2723c91717bc0f3e292fd2e80460a1658ad8d98f387440e53966ce67
            env:
              TZ: Europe/Paris
              DEBUG: false
              GQL_DEBUG: false
              BIND_IP: "0.0.0.0"
              BIND_PORT: &port 4567
              DOWNLOAD_AS_CBZ: "true"
              WEB_UI_CHANNEL: "preview"
              AUTO_DOWNLOAD_CHAPTERS: "false"
              AUTO_DOWNLOAD_EXCLUDE_UNREAD: "false"
              MAX_SOURCES_IN_PARALLEL: 6
              UPDATE_EXCLUDE_UNREAD: "false"
              UPDATE_EXCLUDE_STARTED: "false"
              UPDATE_EXCLUDE_COMPLETED: "false"
              UPDATE_MANGA_INFO: "true"
              UPDATE_INTERVAL: 12
              BACKUP_INTERVAL: 1
              BACKUP_TTL: 14
              EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
              BASIC_AUTH_ENABLED: "false"
              BASIC_AUTH_USERNAME: ""
              BASIC_AUTH_PASSWORD: ""
              FLARESOLVERR_ENABLED: "true"
              FLARESOLVERR_URL: "flaresolverr.services.svc.cluster.local:8191"
              FLARESOLVERR_TIMEOUT: 60
              FLARESOLVERR_SESSION_NAME: "suwayomi"
              FLARESOLVERR_SESSION_TTL: 15
            ports:
              - containerPort: *port
                name: http
                protocol: TCP
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false # We disable as it needs to write the config
              capabilities:
                drop:
                  - ALL
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    persistence:
      config:
        labels:
          homelab/backup-resource: "true"
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ${fastdata_storage}-ha
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
      downloads:
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_download}
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk/downloads
            # subPath: Downloads/suwayomi/sources
