---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: suwayomi
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 10.4.0
    digest: sha256:8a550bbc96a7b48928e902b8da8fd5b1dbb95b8599321c1d116698df46cb6f3d
  url: oci://oci.trueforge.org/truecharts/tachidesk-docker
