---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: suwayomi
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 10.4.2
    digest: sha256:9fcb817886f4e1f681a8337d47190473e6c0008111ce5a32ef436fb0166b7fcc
  url: oci://oci.trueforge.org/truecharts/tachidesk-docker
