---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-credentials
spec:
  data:
    # - secretKey: private_key
    #   remoteRef:
    #     key: external-github-sa
    #     property: identity
    # - secretKey: known_hosts
    #   remoteRef:
    #     key: external-github-sa
    #     property: known_hosts
    - secretKey: username
      remoteRef:
        key: external-github-sa
        property: username
    - secretKey: password
      remoteRef:
        key: external-github-sa
        property: password

  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/git-0: https://github.com
      data:
        # ssh-privatekey: '{{ `{{ .private_key }}` }}'
        # known_hosts: '{{ `{{ .known_hosts }}` }}'
        username: '{{ `{{ .username }}` }}'
        password: '{{ `{{ .password }}` }}'
      engineVersion: v2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-build-bot
secrets:
  - name: github-credentials