apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-authentik-blueprints
  labels:
    goauthentik_blueprint: "1"
data:
  forgejo_entitlements.yaml: |
    version: 1
    metadata:
      name: forgejo-entitlements-blueprints
      labels:
        blueprints.goauthentik.io/description: |
          This blueprint configures application entitlements for Forgejo

    entries:
      # Application entitlements
      # 1. Users
      - model: authentik_core.applicationentitlement
        id: gituser-entitlement
        identifiers:
          name: gituser
          app: !Find [authentik_core.application, [name, "forgejo"]]
        attrs: {}

      # 2. Administrators
      - model: authentik_core.applicationentitlement
        id: gitadmin-entitlement
        identifiers:
          name: gitadmin
          app: !Find [authentik_core.application, [name, "forgejo"]]
        attrs: {}

      # 3. Restricted Users
      - model: authentik_core.applicationentitlement
        id: gitrestricted-entitlement
        identifiers:
          name: gitrestricted
          app: !Find [authentik_core.application, [name, "forgejo"]]
        attrs: {}

      # Policy bindings
      - model: authentik_policies.policybinding
        identifiers:
          target: !KeyOf gitadmin-entitlement
          order: 0
        attrs:
          group: !Find [authentik_core.group, [name, "authentik Admins"]]

      - model: authentik_policies.policybinding
        identifiers:
          target: !KeyOf gituser-entitlement
          order: 0
        attrs:
          group: !Find [authentik_core.group, [name, "app: forgejo"]]
