---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secret
spec:
  data:
    - secretKey: uuid
      remoteRef:
        key: external-forgejo-secrets
        property: uuid
    - secretKey: token
      remoteRef:
        key: external-forgejo-secrets
        property: token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        uuid: "{{ .uuid }}"
        token: "{{ .token }}"
      engineVersion: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-signing-secret
spec:
  data:
    - secretKey: signing_private_key
      remoteRef:
        key: external-forgejo-secrets
        property: signing_private_key
    - secretKey: signing_public_key
      remoteRef:
        key: external-forgejo-secrets
        property: signing_public_key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        # key must be set to privateKey #https://code.forgejo.org/forgejo-helm/forgejo-helm/src/commit/c48209b03e3af7ff68045b2ce5a145f9da5eb563/templates/gitea/deployment.yaml#L432
        privateKey: "{{ .signing_private_key }}"
        privateKey.pub: "{{ .signing_public_key }}"
      engineVersion: v2
