---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-git
  labels:
    homelab/backup-resource: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${fastdata_storage}-ha
  volumeMode: Filesystem
