---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name firecrawl-api-key
spec:
  dataFrom:
    - extract:
        key: firecrawl-bull-key
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: services-secretstore
  target:
    name: *name
    creationPolicy: Owner
    deletionPolicy: Retain
